= ServiceTalk

ServiceTalk is a JVM network application framework with APIs tailored to specific protocols (e.g. HTTP/1.x,
HTTP/2.x, etc...) and supports multiple programming paradigms.

It is built on link:https://netty.io[Netty] and is designed to provide most of the performance/scalability benefits of
Netty for common networking protocols used in service to service communication. ServiceTalk provides server support and
"smart client" like features such as client-side load balancing and service discovery integration.

See the link:https://docs.servicetalk.io/[ServiceTalk docs] for more information.

== Getting Started

All ServiceTalk released artifacts are available in link:https://repo1.maven.org/maven2/io/servicetalk/[the Maven central repository].

The easiest way to get started is to add ServiceTalk's bill-of-material (BOM) dependency to your project's build.

.Maven, pom/xml
[source,xml]
----
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>io.servicetalk</groupId>
      <artifactId>servicetalk-bom</artifactId>
      <version>${servicetalk.version}</version>
      <type>pom</type>
      <scope>import</scope>
    </dependency>
  </dependencies>
</dependencyManagement>
----

.Gradle 5, build.gradle
[source,groovy]
----
implementation platform("io.servicetalk:servicetalk-bom:$serviceTalkVersion")
----

.Gradle 4
[source,groovy]
----
implementation "io.servicetalk:servicetalk-bom:$serviceTalkVersion" // <1>

enableFeaturePreview("IMPROVED_POM_SUPPORT") // <2>
----
<1> in _build.gradle_
<2> in _settings.gradle_

With this in place, you can add the ServiceTalk module dependencies you need without specifying their versions.

Refer to the link:https://docs.servicetalk.io/[ServiceTalk docs] for various examples that will get you started with the different features of ServiceTalk.

NOTE: Builds of the development version are available
      in link:https://oss.sonatype.org/content/repositories/snapshots/io/servicetalk/[Sonatype's snapshots Maven repository].

=== Contributor Setup

IMPORTANT: If you're intending to contribute to ServiceTalk,
           make sure to first read the xref:CONTRIBUTING.adoc[contribution guidelines].

ServiceTalk uses link:https://gradle.org[Gradle] as its build tool and only requires JDK 8 or higher to be pre-installed.
ServiceTalk ships with the Gradle Wrapper, which means that there is no need to install Gradle on your machine beforehand.

IMPORTANT: ServiceTalk's source code is UTF-8 encoded: make sure your filesystem supports it before attempting to build
the project. Setting the `JAVA_TOOL_OPTIONS` env var to `-Dfile.encoding=UTF-8` should help building the project in
non-UTF-8 environments. Editors and IDEs must also support UTF-8 in order to successfully edit ServiceTalk's source code.

You should be able to run the following command to build ServiceTalk:

[source,shell]
----
$ ./gradlew build
----

The supported IDE is link:https://www.jetbrains.com/idea[IntelliJ IDEA].
In order to generate IntelliJ IDEA project files for ServiceTalk,
you can run the following command:

[source,shell]
----
$ ./gradlew idea
----

When done, running one of following commands would open ServiceTalk in IntelliJ:

.Generic
[source,shell]
----
$ idea .
----

.macOS
[source,shell]
----
$ open servicetalk.ipr
----
