== ServiceTalk protoc plugin for gRPC

This module implements the
link:https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/compiler/plugin.proto[Protoc Plugin Interface]
and generates ServiceTalk code for service definitions contained in `.proto` files.

It is recommended to automate the usage of this plugin in your build via
link:https://github.com/google/protobuf-gradle-plugin[protobuf-gradle-plugin] or
link:https://www.xolstice.org/protobuf-maven-plugin[protobuf-maven-plugin]. Both options
are demonstrated in the
link:{source-root}/servicetalk-examples/grpc/helloworld[gRPC HelloWorld Example].

=== Options
This plugin supports the following
link:https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.compiler.command_line_interface[options]:

==== `javaDocs=<true|false>`
Control if `javadoc` is generated by this plugin. Here is an example of how you can specify this option:

[source,gradle]
----
task.plugins {
  servicetalk_grpc {
    option 'javaDocs=false'
  }
}
----

==== `typeNameSuffix=<value>`
Appends the <value> onto service type names generated by this plugin. This helps to avoid service type name
collisions if other protoc plugins are generating code in the same gradle project, or in the same package name.

If you are using the
link:https://github.com/google/protobuf-gradle-plugin#configure-what-to-generate[protobuf-gradle-plugin] this is how you
can specify an option:

[source,gradle]
----
task.plugins {
  servicetalk_grpc {
    option 'typeNameSuffix=Foo'
  }
}
----
