// Configure {source-root} values based on how this document is rendered: on GitHub or not
ifdef::env-github[]
:source-root:
endif::[]
ifndef::env-github[]
ifndef::source-root[:source-root: https://github.com/apple/servicetalk/blob/{page-origin-refname}]
endif::[]

== ServiceTalk protoc plugin for gRPC

This module implements the
link:https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/compiler/plugin.proto[Protoc Plugin Interface]
to generate ServiceTalk code for service definitions contained in `.proto` files. It's also a convenient way of adding
all required transitive dependencies for the generated code by simply adding `io.servicetalk:servicetalk-grpc-protobuf`
as a dependency to your classpath.

It is recommended to automate the usage of this plugin in your build via
link:https://github.com/google/protobuf-gradle-plugin[protobuf-gradle-plugin] or
link:https://www.xolstice.org/protobuf-maven-plugin[protobuf-maven-plugin]. Both options
are demonstrated in the
link:{source-root}/servicetalk-examples/grpc/helloworld[gRPC HelloWorld Example].

=== Options
This plugin supports the following
link:https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.compiler.command_line_interface[options]:

==== `javaDocs=<true|false>`  (default: true)
Control if `javadoc` is generated by this plugin. Here is an example of how you can specify this option with gradle:

[source,gradle]
----
task.plugins {
  servicetalk_grpc {
    option 'javaDocs=false'
  }
}
----

And with Maven:

[source, xml]
----
<protocPlugin>
  <id>servicetalk-grpc-protoc</id>
  <!-- more params -->
  <args>
    <arg>javaDocs=false</arg>
  </args>
</protocPlugin>
----

==== `typeNameSuffix=<value>` (default: not enabled)
Appends the <value> onto service type names generated by this plugin. This helps to avoid service type name
collisions if other protoc plugins are generating code in the same gradle project, or in the same package name.

If you are using the
link:https://github.com/google/protobuf-gradle-plugin#configure-what-to-generate[protobuf-gradle-plugin] this is how you
can specify an option:

[source,gradle]
----
task.plugins {
  servicetalk_grpc {
    option 'typeNameSuffix=Foo'
  }
}
----

And with Maven:

[source, xml]
----
<protocPlugin>
  <id>servicetalk-grpc-protoc</id>
  <!-- more params -->
  <args>
    <arg>typeNameSuffix=Foo</arg>
  </args>
</protocPlugin>
----

==== `skipDeprecated=<true|false>` (default: false)
Instructs the generator to remove all deprecated methods and fields from the generated code, as well as remove calls
to deprecated code either to internal ServiceTalk libraries, or outside. This will almost certainly cause breaking changes
to code that uses these deprecated methods but will be forward compatible.

If you are using the
link:https://github.com/google/protobuf-gradle-plugin#configure-what-to-generate[protobuf-gradle-plugin] this is how you
can specify an option:

[source,gradle]
----
task.plugins {
  servicetalk_grpc {
    option 'skipDeprecated=true'
  }
}
----

And with Maven:

[source, xml]
----
<protocPlugin>
  <id>servicetalk-grpc-protoc</id>
  <!-- more params -->
  <args>
    <arg>skipDeprecated=true</arg>
  </args>
</protocPlugin>
----

==== `defaultServiceMethods=<true|false> (default: false)`
Generates default service interface methods to ensure implementations will continue to compile as the API is evolved.

NOTE: We plan to flip the default value of this option to `true` in the next major release.

If you are using the
link:https://github.com/google/protobuf-gradle-plugin#configure-what-to-generate[protobuf-gradle-plugin] this is how you
can specify an option:

[source,gradle]
----
task.plugins {
  servicetalk_grpc {
    option 'defaultServiceMethods=true'
  }
}
----

And with Maven:

[source, xml]
----
<protocPlugin>
  <id>servicetalk-grpc-protoc</id>
  <!-- more params -->
  <args>
    <arg>defaultServiceMethods=true</arg>
  </args>
</protocPlugin>
----
