include::ROOT:partial$component-attributes.adoc[]
= HTTP

This module defines the ServiceTalk client and server API for the link:https://tools.ietf.org/html/rfc7231[HTTP/1.x]
protocol. This module supports all the different xref:servicetalk:ROOT:introduction.adoc#programmingp-paradigms[Programming Paradigms] for client
and server. Here is a quick start example of the xref:servicetalk:ROOT:introduction.adoc#blocking-and-aggregated[blocking and aggregated]
paradigm:

==== Blocking Client
See
link:{sourceroot}servicetalk-examples/http/helloworld/src/main/java/io/servicetalk/examples/http/helloworld/blocking/BlockingHelloWorldClient.java[BlockingHelloWorldClient].
[source, java]
----
try (BlockingHttpClient client = HttpClients.forSingleAddress("localhost", 8080).buildBlocking()) {
  HttpResponse response = client.request(client.get("/sayHello"));
  // use the response
}
----

==== Blocking Server
See
link:{sourceroot}servicetalk-examples/http/helloworld/src/main/java/io/servicetalk/examples/http/helloworld/blocking/BlockingHelloWorldServer.java[BlockingHelloWorldServer].
[source, java]
----
HttpServers.forPort(8080)
  .listenBlockingAndAwait((ctx, request, responseFactory) ->
    responseFactory.ok().payloadBody("Hello World!", textSerializer()))
  .awaitShutdown();
----

=== Extensibility and Filters
The design of this protocol involves configuring builders for core protocol concerns, and then appending `Filters` for
extensibility. `Filters` are described in more detail below (e.g. <<Service Filters>>, <<Client Filters>>) but in
general they facilitate user code to filter/intercept/modify the request/response processing. `Filters` can be used for
cross-cutting concerns such as authentication, authorization, logging, metrics, tracing, etc...

== Server
The server side is built around the concept of `Service`. A `Service` is where your business logic lives. ServiceTalk's
HTTP module will interact with a single service which is provided by the user via `HttpServers`. The flow of data from
the socket to the HTTP `Service` is visualized as follows:

[ditaa]
----
+--------+ request  +---------+       +---------+
|        |--------->|  HTTP   |------>|  HTTP   |
| Socket |          | Decoder |       | Service |
|        |<---------| Encoder |<------|         |
+--------+ response +---------+       +---------+
----

Each `Service` has access to a
link:{sourceroot}servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpServiceContext.java[HttpServiceContext] which provides additional context
(via link:{sourceroot}servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ConnectionContext.java[ConnectionContext]) into the
`Connection`/transport details for each request/response. This means that the `HttpService` may be invoked for multiple
connections, from different threads, and even concurrently.

=== Service Filters
Filters provide a means to filter/intercept and modify each request/response life cycle. `Service` Filters are used to
implement
link:{sourceroot}servicetalk-opentracing-http/src/main/java/io/servicetalk/opentracing/http/TracingHttpServiceFilter.java[tracing]
metrics, logging,
link:{sourceroot}servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/auth/BasicAuthHttpServiceFilter.java[basic auth],
and any other extension that needs request/response level visibility. The diagram below describes the control flow
as related to `Service` filters:

[ditaa]
----
+--------+ request  +---------+       +---------+       +---------+       +---------+
|        |--------->|  HTTP   |------>|  HTTP   |------>|  HTTP   |------>|  HTTP   |
| Socket |          | Decoder |       | Service |       | Service |       | Service |
|        |<---------| Encoder |<------| Filter 1|<------| Filter n|<------|         |
+--------+ response +---------+       +---------+       +---------+       +---------+
----

To implement a `Service` filter you should implement the
link:{sourceroot}servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpServiceFilterFactory.java[Service Filter Factory] and append it
on the `HttpServerBuilder` via
link:{sourceroot}servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpServerBuilder.java[HttpServerBuilder#appendServiceFilter(..)].

NOTE: Currently we only support writing `Filters` for the <<asynchronous-and-streaming, Asynchronous and Streaming>>
programming paradigm but plan to add support for the others soon. The
<<asynchronous-and-streaming, Asynchronous and Streaming>> can be used with a `Service` in any other programming
paradigm.

[#routers]
=== Routers
In practice it is common for a HTTP `Service` to handle many different types of request(s) that all have unique
processing requirements. The control flow in ServiceTalk is represented by a "Router". A "Router" is a `Service` that
owns the responsibility of multiplexing the control flow. ServiceTalk does not mandate a specific "Router"
implementation but provides a couple reference implementations for common use cases (e.g.
link:{sourceroot}servicetalk-http-router-predicate[Predicate Router] and
link:{sourceroot}servicetalk-http-router-jersey[JAX-RS via Jersey]). The general component diagram of a "Router" is as follows:

[ditaa]
----
                                                                +---------+
                                                        /------>| Route 1 |
                                                        |       +---------+
+--------+ request  +---------+       +---------+       |
|        |--------->|  HTTP   |------>|  HTTP   |       |       +---------+
| Socket |          | Decoder |       | Service |<------+------>| Route 2 |
|        |<---------| Encoder |<------| Router  |       |       +---------+
+--------+ response +---------+       +---------+       |
                                                        |       +---------+
                                                        \------>| Route n |
                                                                +---------+
----

[#service-programming-paradigms]
=== Service Programming Paradigms
HTTP `Service` supports all the variations described in xref:servicetalk:ROOT:introduction.adoc#programming-paradigms[Programming Paradigms].

[#blocking-and-aggregated]
==== Blocking and Aggregated
This programming paradigm exposes the request (including the payload body) as a single aggregated object, and the
response (including the payload body) is also a single aggregated object. The `Service` directly returns the response
object and there are no asynchronous primitives involved.

See
link:{sourceroot}servicetalk-examples/http/helloworld/src/main/java/io/servicetalk/examples/http/helloworld/blocking/BlockingHelloWorldServer.java[BlockingHelloWorldServer].
[source, java]
----
HttpServers.forPort(8080)
  .listenBlockingAndAwait((ctx, request, responseFactory) ->
    responseFactory.ok().payloadBody("Hello World!", textSerializer()))
  .awaitShutdown();
----

[#blocking-and-streaming]
==== Blocking and Streaming
This programming paradigm exposes the request payload body as an
link:https://docs.oracle.com/javase/8/docs/api/java/lang/Iterable.html[Iterable] of
link:{sourceroot}servicetalk-buffer-api/src/main/java/io/servicetalk/buffer/api/Buffer.java[Buffer]s and the response payload
body is written via an
link:{sourceroot}servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpPayloadWriter.java[HttpPayloadWriter] or an
link:{sourceroot}servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpOutputStream.java[HttpOutputStream]. There are no asynchronous primitives
involved.

See
link:{sourceroot}servicetalk-examples/http/helloworld/src/main/java/io/servicetalk/examples/http/helloworld/blocking/streaming/BlockingHelloWorldStreamingServer.java[BlockingHelloWorldStreamingServer].
[source, java]
----
HttpServers.forPort(8080).listenBlockingStreamingAndAwait((ctx, request, response) -> {
  try (HttpPayloadWriter<String> payloadWriter = response.sendMetaData(textSerializer())) {
    payloadWriter.write("Hello");
    payloadWriter.write(" World!");
  }
}).awaitShutdown();
----

[#asynchronous-and-aggregated]
==== Asynchronous and Aggregated
This programming paradigm exposes the request payload body as a single aggregated object, and the response payload body
is also a single aggregated object. The `Service` provides the response by completing a
link:{sourceroot}servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Single.java[Single] which is an
asynchronous primitive.

See
link:{sourceroot}servicetalk-examples/http/helloworld/src/main/java/io/servicetalk/examples/http/helloworld/async/HelloWorldServer.java[HelloWorldServer].
[source, java]
----
HttpServers.forPort(8080)
  .listenAndAwait((ctx, request, responseFactory) ->
    succeeded(responseFactory.ok().payloadBody("Hello World!", textSerializer())))
  .awaitShutdown();
----

[#asynchronous-and-streaming]
==== Asynchronous and Streaming
This programming paradigm exposes the request payload body as a
link:{sourceroot}servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java[Publisher] typically of
link:{sourceroot}servicetalk-buffer-api/src/main/java/io/servicetalk/buffer/api/Buffer.java[Buffer]s (although other types like
file regions may be added), the response meta-data is provided by completing a
link:{sourceroot}servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Single.java[Single], and the response
payload body is written via a
link:{sourceroot}servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java[Publisher].

See
link:{sourceroot}servicetalk-examples/http/helloworld/src/main/java/io/servicetalk/examples/http/helloworld/async/streaming/HelloWorldStreamingServer.java[HelloWorldStreamingServer].
[source, java]
----
HttpServers.forPort(8080)
  .listenStreamingAndAwait((ctx, request, responseFactory) ->
    succeeded(responseFactory.ok()
      .payloadBody(from("Hello", " World!"), textSerializer())))
  .awaitShutdown();
----

== Client
A `Client` is generally responsible for managing multiple `Connections`. There are a few flavors of HTTP Clients:

==== SingleAddress Client
This `Client` will connect to a single unresolved address, that is provided while creating the client. The unresolved
address is resolved via an asynchronous DNS resolver by default (see <<Service Discovery>>). This `Client` is for use
cases where you want to issue requests to a single service (that may have multiple instances).

==== MultiAddress Client
This `Client` parses the link:https://tools.ietf.org/html/rfc7230#section-5.3[request-target] to determine the remote
address for each request. This `Client` simulates a browser type of use case.

Each of the above ``Client``s can be created via the
link:{sourceroot}servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpClients.java[HttpClients] static factory.

The `Client` manages multiple `Connections` via a
link:{sourceroot}servicetalk-client-api/src/main/java/io/servicetalk/client/api/LoadBalancer.java[LoadBalancer]. The control flow
of a request/response can be visualized in the below diagram:

[ditaa]
----
                                             +--------------+     +----------------------+     +--------+
                                        /--->| Connection 1 |<--->| HTTP Decoder/Encoder |<--->| Socket |
                                        |    +--------------+     +----------------------+     +--------+
+--------+ request  +--------------+    |
|        |--------->|              |    |    +--------------+     +----------------------+     +--------+
| Client |          | LoadBalancer |<---+--->| Connection 2 |<--->| HTTP Decoder/Encoder |<--->| Socket |
|        |<---------|              |    |    +--------------+     +----------------------+     +--------+
+--------+ response +--------------+    |
                                        |    +--------------+     +----------------------+     +--------+
                                        \--->| Connection x |<--->| HTTP Decoder/Encoder |<--->| Socket |
                                             +--------------+     +----------------------+     +--------+
----

The link:{sourceroot}servicetalk-client-api/src/main/java/io/servicetalk/client/api/LoadBalancer.java[LoadBalancer] is consulted
for each request to determine which connection should be used. The `LoadBalancer` interface is extensible and
the reference implementation provides a
link:{sourceroot}servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancer.java[Round Robin algorithm].

=== Client Filters
Filters provide a means to filter/intercept and modify each request/response life cycle. `Client` Filters are used to
implement
link:{sourceroot}servicetalk-opentracing-http/src/main/java/io/servicetalk/opentracing/http/TracingHttpRequesterFilter.java[tracing]
metrics, logging, authorization, and any other extension that needs request/response level visibility.

[ditaa]
----
                                                                             +--------------+     +----------------------+     +--------+
                                                                        /--->| Connection 1 |<--->| HTTP Decoder/Encoder |<--->| Socket |
                                                                        |    +--------------+     +----------------------+     +--------+
+--------+ request  +---------+     +---------+     +--------------+    |
|        |--------->|         |---->|         |---->|              |    |    +--------------+     +----------------------+     +--------+
| Client |          | Client  |     | Client  |     | LoadBalancer |<---+--->| Connection 2 |<--->| HTTP Decoder/Encoder |<--->| Socket |
|        |<---------| Filter 1|<----| Filter n|<----|              |    |    +--------------+     +----------------------+     +--------+
+--------+ response +---------+     +---------+     +--------------+    |
                                                                        |    +--------------+     +----------------------+     +--------+
                                                                        \--->| Connection x |<--->| HTTP Decoder/Encoder |<--->| Socket |
                                                                             +--------------+     +----------------------+     +--------+
----

To implement a `Client` filter you should implement the
link:{sourceroot}servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpClientFilterFactory.java[Client Filter Factory] and append it on
the `HttpClientBuilder` via
link:{sourceroot}servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpClientBuilder.java[HttpClientBuilder#appendClientFilter(..)].

NOTE: Currently we only support writing `Filters` for the <<client-asynchronous-and-streaming, Asynchronous and Streaming>>
programming paradigm but plan to add support for the others soon. The
<<client-asynchronous-and-streaming, Asynchronous and Streaming>> can be used with a `Client` in any other programming
paradigm.

=== Connection Filters
The `Client` doesn't have visibility into `Connection` specific information. For example, the `Connection` layer knows
about transport details such as connected remote address and other elements in the
link:{sourceroot}servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ConnectionContext.java[ConnectionContext].
If you have use cases that require this information in the request/response control flow you can use a
`Connection Filter`. The diagram below illustrates how the `Connection Filter` interacts with the request/response
control flow.

[ditaa]
----
                                             +---------------------+     +---------------------+     +--------------+     +----------------------+     +--------+
                                        /--->| Connection Filter 1 |<--->| Connection Filter n |<--->| Connection 1 |<--->| HTTP Decoder/Encoder |<--->| Socket |
                                        |    +---------------------+     +---------------------+     +--------------+     +----------------------+     +--------+
+--------+ request  +--------------+    |
|        |--------->|              |    |    +---------------------+     +---------------------+     +--------------+     +----------------------+     +--------+
| Client |          | LoadBalancer |<---+--->| Connection Filter 1 |<--->| Connection Filter n |<--->| Connection 2 |<--->| HTTP Decoder/Encoder |<--->| Socket |
|        |<---------|              |    |    +---------------------+     +---------------------+     +--------------+     +----------------------+     +--------+
+--------+ response +--------------+    |
                                        |    +---------------------+     +---------------------+     +--------------+     +----------------------+     +--------+
                                        \--->| Connection Filter 1 |<--->| Connection Filter n |<--->| Connection x |<--->| HTTP Decoder/Encoder |<--->| Socket |
                                             +---------------------+     +---------------------+     +--------------+     +----------------------+     +--------+
----

=== Service Discovery
Another core component of the `Client` is the
link:{sourceroot}servicetalk-client-api/src/main/java/io/servicetalk/client/api/ServiceDiscoverer.java[ServiceDiscoverer]. The
`ServiceDiscoverer` is responsible for resolving a service address into a set of resolved addresses used to create
`Connection`(s) by the `LoadBalancer`. The default implementation for HTTP is DNS and will resolve the IP addresses of
each service address every link:https://tools.ietf.org/html/rfc1035#section-3.2.1[TTL] seconds. ``ServiceDiscoverer``s
are typically not invoked in the request/response path and addresses are resolved "out of band", a.k.a in the
background.

[ditaa]
----
                     +------------+
                     |   Service  |
                     | Discoverer |
                     +------------+
                           ^
                           |
                           |                 +--------------+
                           |            /--->| Connection 1 |
                           V            |    +--------------+
+--------+ request  +--------------+    |
|        |--------->|              |    |    +--------------+
| Client |          | LoadBalancer |<---+--->| Connection 2 |
|        |<---------|              |    |    +--------------+
+--------+ response +--------------+    |
                                        |    +--------------+
                                        \--->| Connection x |
                                             +--------------+
----

[#client-programming-paradigms]
=== Client Programming Paradigms
HTTP Client supports all the variations described in xref:servicetalk:ROOT:introduction.adoc#programming-paradigms[Programming Paradigms].

[#client-blocking-and-aggregated]
==== Blocking and Aggregated
This programming paradigm expects the request (including the payload body) as a single aggregated object, and the
response (including the payload body) is also a single aggregated object. The `Client` directly returns the response
object and there are no asynchronous primitives involved.

See
link:{sourceroot}servicetalk-examples/http/helloworld/src/main/java/io/servicetalk/examples/http/helloworld/blocking/BlockingHelloWorldClient.java[BlockingHelloWorldClient]
[source, java]
----
try (BlockingHttpClient client = HttpClients.forSingleAddress("localhost", 8080).buildBlocking()) {
  HttpResponse response = client.request(client.get("/sayHello"));
  // use the response
}
----

[#client-blocking-and-streaming]
==== Blocking and Streaming
This programming paradigm expects the request payload body as an
link:https://docs.oracle.com/javase/8/docs/api/java/lang/Iterable.html[Iterable] of
link:{sourceroot}servicetalk-buffer-api/src/main/java/io/servicetalk/buffer/api/Buffer.java[Buffer]s and the response payload
body is consumed via an
link:https://docs.oracle.com/javase/8/docs/api/java/lang/Iterable.html[Iterable] of
link:{sourceroot}servicetalk-buffer-api/src/main/java/io/servicetalk/buffer/api/Buffer.java[Buffer]s. There are no asynchronous
primitives involved.

See
link:{sourceroot}servicetalk-examples/http/helloworld/src/main/java/io/servicetalk/examples/http/helloworld/blocking/streaming/BlockingHelloWorldStreamingClient.java[BlockingHelloWorldStreamingClient]
[source, java]
----
try (BlockingStreamingHttpClient client = HttpClients.forSingleAddress("localhost", 8080)
      .buildBlockingStreaming()) {
  BlockingStreamingHttpResponse response = client.request(client.get("/sayHello"));
  System.out.println(response.toString((name, value) -> value));
  try (BlockingIterator<String> payload = response.payloadBody(textDeserializer()).iterator()) {
    while (payload.hasNext()) {
      System.out.println(payload.next());
    }
  }
}
----

[#client-asynchronous-and-aggregated]
==== Asynchronous and Aggregated
This programming paradigm expects the request payload body as a single aggregated object, and the response payload body
is also a single aggregated object. The `HttpClient` provides the response via a
link:{sourceroot}servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Single.java[Single] which is an
asynchronous primitive.

See
link:{sourceroot}servicetalk-examples/http/helloworld/src/main/java/io/servicetalk/examples/http/helloworld/async/HelloWorldClient.java[HelloWorldClient]
[source, java]
----
try (HttpClient client = HttpClients.forSingleAddress("localhost", 8080).build()) {
// This example is demonstrating asynchronous execution, but needs to prevent the main
// thread from exiting before the response has been processed. This isn't typical usage
// for a streaming API but is useful for demonstration purposes.
  CountDownLatch responseProcessedLatch = new CountDownLatch(1);
  client.request(client.get("/sayHello"))
        .doFinally(responseProcessedLatch::countDown)
        .subscribe(resp -> {
     System.out.println(resp.toString((name, value) -> value));
     System.out.println(resp.payloadBody(textDeserializer()));
  });

  responseProcessedLatch.await();
}
----

[#client-asynchronous-and-streaming]
==== Asynchronous and Streaming
This programming paradigm expects the request payload body as a
link:{sourceroot}servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java[Publisher] typically of
link:{sourceroot}servicetalk-buffer-api/src/main/java/io/servicetalk/buffer/api/Buffer.java[Buffer]s (although other types like
file regions may be added), the response meta-data is provided via a
link:{sourceroot}servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Single.java[Single], and the response
payload body is written via a
link:{sourceroot}servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java[Publisher].

See
link:{sourceroot}servicetalk-examples/http/helloworld/src/main/java/io/servicetalk/examples/http/helloworld/async/streaming/HelloWorldStreamingClient.java[HelloWorldStreamingClient]
[source, java]
----
try (StreamingHttpClient client = HttpClients.forSingleAddress("localhost", 8080).buildStreaming()) {
// This example is demonstrating asynchronous execution, but needs to prevent the main thread from
// exiting before the response has been processed. This isn't typical usage for a streaming API but
// is useful for demonstration purposes.
  CountDownLatch responseProcessedLatch = new CountDownLatch(1);
  client.request(client.get("/sayHello"))
        .beforeOnSuccess(response -> System.out.println(response.toString((name, value) -> value)))
        .flatMapPublisher(resp -> resp.payloadBody(textDeserializer()))
        .doFinally(responseProcessedLatch::countDown)
        .forEach(System.out::println);

  responseProcessedLatch.await();
}
----

== Serialization
Serialization factories are made available in the
link:{sourceroot}servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpSerializationProviders.java[HttpSerializationProviders] static factory
class.

The core abstractions
link:{sourceroot}servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpDeserializer.java[HttpDeserializer] and
link:{sourceroot}servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpSerializer.java[HttpSerializer] are designed to be coupled to a
specific Java type `T` and accessed via a
link:{sourceroot}servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpSerializationProvider.java[HttpSerializationProvider]. The
link:{sourceroot}servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpDeserializer.java[HttpDeserializer] and
link:{sourceroot}servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpSerializer.java[HttpSerializer] are also designed to handle the HTTP
headers data behind the scenes. This means either checking if `content-type` format is compatible with the
deserialization format and also adding a `content-type` header identifying the resulting serialization format.
