// Configure {source-root} values based on how this document is rendered: on GitHub or not
ifdef::env-github[]
:source-root:
endif::[]
ifndef::env-github[]
ifndef::source-root[:source-root: https://github.com/apple/servicetalk/blob/{page-origin-refname}]
endif::[]

= HTTP Examples

The link:{source-root}/servicetalk-examples/http[`http`]
folder contains examples for the https://tools.ietf.org/html/rfc7231[HTTP] protocol.

[#HelloWorld]
== Hello World

An obligatory "Hello World" example for HTTP.

=== Asynchronous + Aggregated

This example demonstrates asynchronous request processing where the payload body is aggregated into a single object
instead of a stream.

* link:{source-root}/servicetalk-examples/http/helloworld/src/main/java/io/servicetalk/examples/http/helloworld/async/HelloWorldServer.java[HelloWorldServer] - a server that demonstrates the asynchronous API and
responds with a simple `Hello World!` response body as a `text/plain`.
* link:{source-root}/servicetalk-examples/http/helloworld/src/main/java/io/servicetalk/examples/http/helloworld/async/HelloWorldClient.java[HelloWorldClient] - a client that sends a `GET` request to the
link:{source-root}/servicetalk-examples/http/helloworld/src/main/java/io/servicetalk/examples/http/helloworld/async/HelloWorldServer.java[server] and receives the response as a single content.
* link:{source-root}/servicetalk-examples/http/helloworld/src/main/java/io/servicetalk/examples/http/helloworld/async/HelloWorldUrlClient.java[HelloWorldUrlClient] - a client that sends a `GET` request to the
specified URL in absolute-form and receives the response as a single content.

=== Asynchronous + Streaming

This example demonstrates asynchronous request processing where the payload body is a stream.

* link:{source-root}/servicetalk-examples/http/helloworld/src/main/java/io/servicetalk/examples/http/helloworld/async/streaming/HelloWorldStreamingServer.java[HelloWorldStreamingServer] - a server that responds with a
stream of `text/plain` payload body for every request.
* link:{source-root}/servicetalk-examples/http/helloworld/src/main/java/io/servicetalk/examples/http/helloworld/async/streaming/HelloWorldStreamingClient.java[HelloWorldStreamingClient] - a client that sends a `GET`
request to the link:{source-root}/servicetalk-examples/http/helloworld/src/main/java/io/servicetalk/examples/http/helloworld/async/streaming/HelloWorldStreamingServer.java[server] and receives the response payload
body as a stream of buffers.
* link:{source-root}/servicetalk-examples/http/helloworld/src/main/java/io/servicetalk/examples/http/helloworld/async/streaming/HelloWorldStreamingUrlClient.java[HelloWorldStreamingUrlClient] - a client that sends a
`GET` request to the specified URL in absolute-form and receives the response payload body as a stream of buffers.

[#blocking-aggregated]
=== Blocking + Aggregated

This example demonstrates blocking request processing where the payload body is aggregated into a single object. The
APIs will block if content is requested but there is no content available.

* link:{source-root}/servicetalk-examples/http/helloworld/src/main/java/io/servicetalk/examples/http/helloworld/blocking/BlockingHelloWorldServer.java[BlockingHelloWorldServer] - a server that demonstrates the
blocking API and responds with a simple `Hello World!` response body as a `text/plain`.
* link:{source-root}/servicetalk-examples/http/helloworld/src/main/java/io/servicetalk/examples/http/helloworld/blocking/BlockingHelloWorldClient.java[BlockingHelloWorldClient] - a client that sends a `GET` request to
the link:{source-root}/servicetalk-examples/http/helloworld/src/main/java/io/servicetalk/examples/http/helloworld/blocking/BlockingHelloWorldServer.java[server] and receives the response payload body as one aggregated
object.
* link:{source-root}/servicetalk-examples/http/helloworld/src/main/java/io/servicetalk/examples/http/helloworld/blocking/BlockingHelloWorldUrlClient.java[BlockingHelloWorldUrlClient] - a client that sends a `GET`
request to the specified URL in absolute-form and receives the response payload body as one aggregated object.

=== Blocking + Streaming

This example demonstrates blocking request processing where the payload body is a blocking iterable stream.

* link:{source-root}/servicetalk-examples/http/helloworld/src/main/java/io/servicetalk/examples/http/helloworld/blocking/streaming/BlockingHelloWorldStreamingServer.java[BlockingHelloWorldStreamingServer] - a server
that responds with an iterable stream of `text/plain` payload body for every request.
* link:{source-root}/servicetalk-examples/http/helloworld/src/main/java/io/servicetalk/examples/http/helloworld/blocking/streaming/BlockingHelloWorldStreamingClient.java[BlockingHelloWorldStreamingClient] - a client
that sends a `GET` request to the link:{source-root}/servicetalk-examples/http/helloworld/src/main/java/io/servicetalk/examples/http/helloworld/blocking/streaming/BlockingHelloWorldStreamingServer.java[server] and
receives the response payload body as a blocking iterable stream of buffers.
* link:{source-root}/servicetalk-examples/http/helloworld/src/main/java/io/servicetalk/examples/http/helloworld/blocking/streaming/BlockingHelloWorldStreamingUrlClient.java[BlockingHelloWorldStreamingUrlClient] - a
client that sends a `GET` request to the specified URL in absolute-form and receives the response payload body as a
blocking iterable stream of buffers.

[#Serialization]
== Serialization

A similar to "Hello World" examples, which demonstrate
link:{source-root}/servicetalk-examples/http/serialization/src/main/java/io/servicetalk/examples/http/serialization/async[asynchronous-aggregated],
link:{source-root}/servicetalk-examples/http/serialization/src/main/java/io/servicetalk/examples/http/serialization/async/streaming[asynchronous-streaming],
link:{source-root}/servicetalk-examples/http/serialization/src/main/java/io/servicetalk/examples/http/serialization/blocking[blocking-aggregated], and
link:{source-root}/servicetalk-examples/http/serialization/src/main/java/io/servicetalk/examples/http/serialization/blocking/streaming[blocking-streaming]
client and server with JSON serialization of simple pojo classes.

Client sends a `POST` request with a JSON payload link:{source-root}/servicetalk-examples/http/serialization/src/main/java/io/servicetalk/examples/http/serialization/CreatePojoRequest.java[PojoRequest] and expects a response
with `Content-Type: application/json` and link:{source-root}/servicetalk-examples/http/serialization/src/main/java/io/servicetalk/examples/http/serialization/PojoResponse.java[MyPojo] as a payload.

[#JAXRS]
== JAX-RS

ServiceTalk provides a JAX-RS implementation that can plugin to ServiceTalk APIs.
This example demonstrates how to use these APIs, and how different API variations (e.g. asynchronous/blocking and
aggregated/streaming) are exposed.

=== Hello world

A simple "Hello World" example built using JAX-RS.

* link:{source-root}/servicetalk-examples/http/jaxrs/src/main/java/io/servicetalk/examples/http/jaxrs/HelloWorldJaxRsServer.java[HelloWorldJaxRsServer] - a JAX-RS based hello world server that demonstrates how to
write blocking as well as asynchronous resource methods.
* link:{source-root}/servicetalk-examples/http/jaxrs/src/main/java/io/servicetalk/examples/http/jaxrs/HelloWorldJaxRsResource.java[HelloWorldJaxRsResource] - a JAX-RS resource having different methods for
blocking and asynchronous interactions.

This example does not have a client yet but one can use curl to send requests like:

----
curl http://localhost:8080/greetings/hello
----

More examples of how to use the resource can be found in the
link:{source-root}/servicetalk-examples/http/jaxrs/src/main/java/io/servicetalk/examples/http/jaxrs/HelloWorldJaxRsResource.java[HelloWorldJaxRsResource] javadocs.

[#MetaData]
== MetaData

This example demonstrates some of the basic functionality of the
link:{source-root}/servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpMetaData.java[HttpMetaData] classes:

- Setting and getting response status.
- Setting and getting query parameters.
- Setting, checking, and getting headers.
- Printing headers without redaction/filtering.

Using the following classes:

- link:{source-root}/servicetalk-examples/http/metadata/src/main/java/io/servicetalk/examples/http/metadata/MetaDataDemoServer.java[MetaDataDemoServer] - A server that provides greetings in various languages.
- link:{source-root}/servicetalk-examples/http/metadata/src/main/java/io/servicetalk/examples/http/metadata/MetaDataDemoClient.java[MetaDataDemoClient] - A client that requests greetings in various languages.

NOTE: This example uses the link:#blocking-aggregated[blocking + aggregated] API, as the metadata API is the same
across all the HTTP APIs.

[#Mutual-TLS]
== Mutual TLS

This example demonstrates how client and server can be configured to do mutual authentication via TLS.

Using the following classes:

- link:{source-root}/servicetalk-examples/http/mutual-tls/src/main/java/io/servicetalk/examples/http/mutualtls/HttpServerMutualTLS.java[HttpServerMutualTLS] - A server that sets the trust manager and key manager, and requires client authentication.
- link:{source-root}/servicetalk-examples/http/mutual-tls/src/main/java/io/servicetalk/examples/http/mutualtls/HttpServerMutualTLS.java[HttpClientMutualTLS] - A client that sets the trust manager and key manager.

NOTE: This example uses the link:#blocking-aggregated[blocking + aggregated] API, as the TLS/SSL configuration API is
the same across all the HTTP APIs.

[#HTTP2]
== HTTP/2

These examples demonstrate how users can configure link:https://tools.ietf.org/html/rfc7540[HTTP/2] transport in
ServiceTalk.

=== HTTP/2 with Prior-Knowledge

This example demonstrates how to configure using
link:https://tools.ietf.org/html/rfc7540#section-3.4[HTTP/2 transport with Prior-Knowledge] for HTTP clients and servers:

- link:{source-root}/servicetalk-examples/http/http2/src/main/java/io/servicetalk/examples/http/http2/priorknowledge/Http2PriorKnowledgeServer.java[Http2PriorKnowledgeServer] -
A server that uses HTTP/2 with Prior Knowledge.
- link:{source-root}/servicetalk-examples/http/http2/src/main/java/io/servicetalk/examples/http/http2/priorknowledge/Http2PriorKnowledgeClient.java[Http2PriorKnowledgeClient] -
A client that uses HTTP/2 with Prior Knowledge.

=== HTTP/2 via ALPN for secure connections

For secure TLS connections link:https://tools.ietf.org/html/rfc7301[ALPN extension] could be used to negotiate the
communication protocol:

- link:{source-root}/servicetalk-examples/http/http2/src/main/java/io/servicetalk/examples/http/http2/alpn/HttpServerWithAlpn.java[HttpServerWithAlpn] -
A server that negotiates HTTP/2 or HTTP/1.1 using ALPN extension for TLS connections.
- link:{source-root}/servicetalk-examples/http/http2/src/main/java/io/servicetalk/examples/http/http2/alpn/HttpClientWithAlpn.java[HttpClientWithAlpn] -
A client that negotiates HTTP/2 or HTTP/1.1 using ALPN extension for TLS connections.

If HTTP/1.x protocol is configured ServiceTalk always fallbacks to it if the peer does not support ALPN extension.

IMPORTANT: Your runtime must support ALPN extension for TLS. The recommended way is to use OpenSSL provider and add
link:https://netty.io/wiki/forked-tomcat-native.html#artifacts[netty-tcnative] artifact to the classpath. If OpenSSL is
not available, make sure your JVM version supports ALPN or use
link:https://www.eclipse.org/jetty/documentation/current/alpn-chapter.html[another provider] that supports it.

NOTE: These examples use the link:#blocking-aggregated[blocking + aggregated] API for demonstration purposes, as the
builder API is the same across all the HTTP APIs.

== Service Composition

An advanced example which demonstrates a composition of various ServiceTalks services in one application.
For more information see xref:http/service-composition.adoc[Service Composition].

[#uds]
== Unix Domain Sockets (UDS)

This example demonstrates how client and server can use unix domain sockets. See
the link:{source-root}/servicetalk-examples/http/uds[uds example code] for more details.

NOTE: This example uses the link:#blocking-aggregated[blocking + aggregated] API, as the UDS configuration API is the
same across all the HTTP APIs.