// Configure {source-root} values based on how this document is rendered: on GitHub or not
ifdef::env-github[]
:source-root:
endif::[]
ifndef::env-github[]
ifndef::source-root[:source-root: https://github.com/apple/servicetalk/blob/{page-origin-refname}]
endif::[]

= Load Balancing

IMPORTANT: Client side Load Balancing is an active work-in-progress, it's used in production, but expect improvements
in the future.

One of the core abstractions in ServiceTalk is its _Client side_
link:{source-root}/servicetalk-client-api/src/main/java/io/servicetalk/client/api/LoadBalancer.java[LoadBalancer]
underpinning the various protocol _Clients_ (eg. HTTP/1.1, HTTP/2, gRPC, etc.).

For scenarios where a client communicates with multiple homogeneous footnote:[belonging to the same service, providing
same capabilities] server instances, managing multiple clients for each service instance is complex. _Client side load
balancing_ makes this easy for the users by transparently communicating with multiple servers. It also provides
opportunities to spread the load across all the servers, minimize latency and reduce error rates thus providing a
resilient and performant system.

== Architecture

ServiceTalk's protocol-specific _Clients_ and _LoadBalancer_ are layered as follows:

[ditaa]
----
                  +-------------------+
                  | ConnectionFactory |
                  +-------------------+      +--------------+     +----------------------+     +--------+
                            |           /--->| Connection 1 |<--->| HTTP Decoder/Encoder |<--->| Socket |
                            V           |    +--------------+     +----------------------+     +--------+
+--------+ request  +--------------+    |
|  HTTP  |--------->| Client-Side  |    |    +--------------+     +----------------------+     +--------+
| Client |          | LoadBalancer |<---+--->| Connection 2 |<--->| HTTP Decoder/Encoder |<--->| Socket |
|        |<---------|              |    |    +--------------+     +----------------------+     +--------+
+--------+ response +--------------+    |
                            ^           |    +--------------+     +----------------------+     +--------+
                            |           \--->| Connection x |<--->| HTTP Decoder/Encoder |<--->| Socket |
                  +-------------------+      +--------------+     +----------------------+     +--------+
                  | ServiceDiscoverer |
                  +-------------------+
----

The load balancer provides similar functionality to a traditional connection pool, but it is consulted on each request
and can be influenced by protocol feedback. This enables building a rich set of features on top such as: intelligent
capacity management, smart connection and host selection, circuit breaking, etc. The _Connection_ abstraction which is
the basis for all protocol-specific _Connections_ allows the
link:{source-root}/servicetalk-client-api/src/main/java/io/servicetalk/client/api/LoadBalancer.java[LoadBalancer]
implementations to be reusable across all the protocols.

The _LoadBalancer_ is able to combine availability information from
link:{source-root}/servicetalk-client-api/src/main/java/io/servicetalk/client/api/ServiceDiscoverer.java[ServiceDiscoverer]
and protocol metrics from the
link:{source-root}/servicetalk-client-api/src/main/java/io/servicetalk/client/api/ConnectionFactory.java[ConnectionFactory]
(e.g. latency, ...) in order to pick a more optimal _Connection_ for each request.

== Implementation

As mentioned earlier the _Client-Side_
link:{source-root}/servicetalk-client-api/src/main/java/io/servicetalk/client/api/LoadBalancer.java[LoadBalancer]
abstraction allows for various protocol-independent _LoadBalancing_ algorithms to be implemented. However, the built-in
Default Load Balancer is a highly featured implementation that we strongly recommend and creating custom load balancing
solutions should be done as a last resort.

=== Default Load Balancer

The ServiceTalk Default Load Balancer is the recommended load balancer. It is a modularization of the
link:{source-root}/servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancer.java[RoundRobinLoadBalancer]
intended to support features necessary for proxyless service-to-service communication. It supports multiple selection
algorithms including Power of Two Choices (P2C) and Round-Robin as well as layer-7 outlier detection mechanisms
including consecutive failure and outlier detection.

See the xref:{page-version}@servicetalk-loadbalancer::defaultloadbalancer.adoc[Default Load Balancer] documentation for
more detail.

