name: PR Builder
permissions:
  contents: read
on:
  pull_request:
    branches: [ main, '0.41', '0.42' ]
    paths-ignore:
      - 'docs/**'
      - 'scripts/**'
      - '.github/pull_request_template.md'
      - '.gitignore'
      - 'gradlew'
      - 'gradlew.bat'
      - '**.adoc'
      - '**.txt'
jobs:
  gradle-wrapper-validation:
    uses: ./.github/workflows/gradle-wrapper-validation.yml
  build:
    needs: gradle-wrapper-validation
    name: JDK ${{ matrix.java }} ${{ matrix.os_label }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [ 8, 11, 17, 21, 25 ]
        os: [ ubuntu-latest ]
        os_label: [ ubuntu ]
        include:
          - java: 11
            os: [self-hosted, macos, general]
            os_label: macos
    steps:
      - name: Checkout Code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Set up JDK ${{ matrix.java }} and JDK 17
        uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
        with:
          java-version: |
            ${{ matrix.java }}
            17
          distribution: 'zulu'
          cache: 'gradle'
      - name: Print JDK Versions
        run: |
          echo "Gradle will run on JDK 17:"
          java -version
          echo "Tests will run on JDK ${{ matrix.java }}:"
          if [ -d "$JAVA_HOME_${{ matrix.java }}_${{ runner.arch }}" ]; then
            "$JAVA_HOME_${{ matrix.java }}_${{ runner.arch }}/bin/java" -version
          fi
      - name: Set Test Java Version
        run: echo "TEST_JAVA_VERSION=${{ matrix.java }}" >> "$GITHUB_ENV"
      - name: Make gradlew Executable
        run: chmod +x gradlew
      - name: Clean Gradle project
        run: ./gradlew --parallel clean
      - name: Build and Test (Linux)
        if: runner.os == 'Linux'
        env:
          JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
        run:  sudo -E env "PATH=$PATH" bash -c "ulimit -l 65536 && ulimit -a && ./gradlew --no-daemon --parallel test"
      - name: Build and Test (non-Linux)
        if: runner.os != 'Linux'
        env:
          JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
        run: ./gradlew --no-daemon --parallel test
      - name: Upload Test Results
        if: '!cancelled()'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          # File location used in ci-prb-reports.yml and must be coordinated.
          name: test-results-${{ matrix.os_label }}-${{ matrix.java }}
          path: '**/build/test-results/test/TEST-*.xml'
