name: PR Quality
permissions:
  contents: read
on:
  pull_request:
    branches: [ main, '0.41', '0.42' ]
    paths-ignore:
      - 'scripts/**'
      - '.github/pull_request_template.md'
      - '.gitignore'
      - 'gradlew'
      - 'gradlew.bat'
      - '*.adoc'
      - '*.txt'
jobs:
  gradle-wrapper-validation:
    uses: ./.github/workflows/gradle-wrapper-validation.yml
  quality:
    needs: gradle-wrapper-validation
    name: JDK ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 11 ] # These are the JDK's we publish artifacts with.
    steps:
      - name: Checkout Code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
        with:
          java-version: |
            17
            ${{ matrix.java }}
          distribution: 'zulu'
          cache: 'gradle'
      - name: Print JDK Version
        run: java -version
      - name: Set Gradle Environment
        run: echo "GRADLE_OPTS=-Dorg.gradle.java.home=$JAVA_HOME_17_${{ runner.arch }}" >> "$GITHUB_ENV"
      - name: Make gradlew Executable
        run: chmod +x gradlew
      - name: Documentation Linter
        run: bash scripts/check-source-root.sh
      - name: Gradle lockfiles validation
        run: bash scripts/check-lockfiles.sh
      - name: Clean Gradle project
        run: ./gradlew --parallel clean
      - name: Build with Gradle
        run: ./gradlew --parallel -Pdependency.analysis.print.build.health=true quality
      - name: Upload CheckStyle Results
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: checkstyle-results-${{ matrix.java }}
          path: '**/build/reports/checkstyle/*.xml'
      - name: Upload PMD Results
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: pmd-results-${{ matrix.java }}
          path: '**/build/reports/pmd/*.xml'
      - name: Upload SpotBugs Results
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: spotbugs-results-${{ matrix.java }}
          path: '**/build/reports/spotbugs/*.xml'
