name: Snapshot Publisher
permissions:
  contents: read
on:
  push:
    branches: [ main, '0.41', '0.42' ]
    tags-ignore:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+.[0-9]+"
    paths-ignore:
      - 'docs/**'
      - 'scripts/**'
      - '.github/pull_request_template.md'
      - '.gitignore'
      - 'gradlew'
      - 'gradlew.bat'
      - '**.adoc'
      - '*.txt'
jobs:
  gradle-wrapper-validation:
    uses: ./.github/workflows/gradle-wrapper-validation.yml
  build:
    needs: gradle-wrapper-validation
    permissions:
      contents: read
      checks: write
    name: Snapshot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Check SNAPSHOT version suffix
        run: if [[ $(cat gradle.properties | grep version= | sed 's/^version=//') =~ .*-SNAPSHOT ]]; then exit 0; else exit 1; fi
      - name: Set up JDK 17
        uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # v5.5.0
        with:
          java-version: 17
          distribution: 'zulu'
          cache: 'gradle'
      - name: Print JDK Version
        run: java -version
      - name: Make gradlew Executable
        run: chmod +x gradlew
      - name: Clean Gradle project
        run: ./gradlew --parallel clean
      - name: Gradle Check project
        run: sudo -E env "PATH=$PATH" bash -c "ulimit -l 65536 && ulimit -a && ./gradlew --no-daemon --parallel check"
      - name: Publish with Gradle
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD }}
          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
          SONATYPE_TOKEN: ${{ secrets.SONATYPE_TOKEN }}
        run: sudo -E env "PATH=$PATH" bash -c "ulimit -l 65536 && ulimit -a && ./gradlew --no-daemon --no-parallel publish"
      - name: Publish Test Results
        if: '!cancelled()'
        uses: EnricoMi/publish-unit-test-result-action@d0a4676d0e0b938bc201470d88276b7c74c712b3 # v2.24.0
        with:
          files: '**/build/test-results/test/TEST-*.xml'
          check_name: Test Report Snapshot
          comment_mode: 'off'
      - name: Publish Checkstyle Report
        if: always()
        uses: jwgmeligmeyling/checkstyle-github-action@50292990e18466f2c5d95d04ff5fab931254fa5f # v1.2
        with:
          name: Checkstyle Report Snapshot
          path: '**/build/reports/checkstyle/*.xml'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish PMD Report
        if: always()
        uses: jwgmeligmeyling/pmd-github-action@322e346bd76a0757c4d54ff9209e245965aa066d # v1.2
        with:
          name: PMD Report Snapshot
          path: '**/build/reports/pmd/*.xml'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish SpotBugs Report
        if: always()
        uses: jwgmeligmeyling/spotbugs-github-action@b8e2c3523acb34c87f14e18cbcd2d87db8c8584e # v1.2
        with:
          name: SpotBugs Report Snapshot
          path: '**/build/reports/spotbugs/*.xml'
          token: ${{ secrets.GITHUB_TOKEN }}
