= ServiceTalk Documentation Website

Repo for ServiceTalk's https://pages.github.com/apple/servicetalk/[documentation website].

The website is built with the https://antora.org[Antora] docsite generator out of https://asciidoctor.org[Asciidoc] docs
maintained in the https://github.com/apple/servicetalk[upstream project].

== Development

=== Generate IntelliJ Project

[source,shell]
----
./gradlew idea
----

=== Build from Local Projects

* Takes upstream project docs from local Git repos assumed to exist in a sibling directory
(see link:site-local.yml[_site-local.yml_]).
* Builds the site (open by clicking the link printed in console output).
* Source code links in the docs link to files locally.
* Validates the generated HTML and checks for dangling links.

This allows previewing of local doc changes made to upstream projects.

[source,shell]
----
./gradlew clean validateLocalSite
----

The `buildLocalSite` task can also be used to quickly build without validating links.

=== Build from Remote Projects

* Fetches upstream project docs from the GitHub repo (see link:site-remote.yml[_site-remote.yml_])
* Builds the site (open by clicking the link printed in console output).
* Source code links in the docs link to github.
* Validates the generated HTML and checks for dangling links.

This is what CI runs.

[source,shell]
----
./gradlew clean validateRemoteSite
----
